# Generated by Django 4.2.5 on 2023-10-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0004_alter_advertisement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='imge',
            field=models.ImageField(default='', upload_to='advertisements/', verbose_name='изображение'),
            preserve_default=False,
        ),
    ]
