# Generated by Django 4.2.5 on 2023-10-02 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0005_advertisement_imge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='imge',
            new_name='image',
        ),
    ]
